/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamAppsNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamAppsNative
#define _Included_org_twopology_steamnetworks4j_SteamAppsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    isSubscribed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_isSubscribed
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    isLowViolence
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_isLowViolence
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    isCybercafe
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_isCybercafe
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    isVACBanned
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_isVACBanned
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    getCurrentGameLanguage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_getCurrentGameLanguage
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    getAvailableGameLanguages
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_getAvailableGameLanguages
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    isSubscribedApp
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_isSubscribedApp
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    isDlcInstalled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_isDlcInstalled
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    getEarliestPurchaseUnixTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_getEarliestPurchaseUnixTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    isSubscribedFromFreeWeekend
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_isSubscribedFromFreeWeekend
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    getDLCCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_getDLCCount
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    installDLC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_installDLC
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    uninstallDLC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_uninstallDLC
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    getAppOwner
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_getAppOwner
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    getAppBuildId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_getAppBuildId
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAppsNative
 * Method:    setDlcContext
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamAppsNative_setDlcContext
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
