/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamMatchmakingServerListResponse */

#ifndef _Included_org_twopology_steamnetworks4j_SteamMatchmakingServerListResponse
#define _Included_org_twopology_steamnetworks4j_SteamMatchmakingServerListResponse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServerListResponse
 * Method:    createProxy
 * Signature: (Lorg/twopology/steamnetworks4j/SteamMatchmakingServerListResponse;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServerListResponse_createProxy
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
