/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamAPI */

#ifndef _Included_org_twopology_steamnetworks4j_SteamAPI
#define _Included_org_twopology_steamnetworks4j_SteamAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamAPI
 * Method:    nativeRestartAppIfNecessary
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamAPI_nativeRestartAppIfNecessary
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAPI
 * Method:    releaseCurrentThreadMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamAPI_releaseCurrentThreadMemory
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAPI
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamAPI_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAPI
 * Method:    nativeShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamAPI_nativeShutdown
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAPI
 * Method:    runCallbacks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamAPI_runCallbacks
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamAPI
 * Method:    isSteamRunningNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamAPI_isSteamRunningNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
