/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamScreenshotsNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamScreenshotsNative
#define _Included_org_twopology_steamnetworks4j_SteamScreenshotsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamScreenshotsNative
 * Method:    createCallback
 * Signature: (Lorg/twopology/steamnetworks4j/SteamScreenshotsCallbackAdapter;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamScreenshotsNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamScreenshotsNative
 * Method:    writeScreenshot
 * Signature: (Ljava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamScreenshotsNative_writeScreenshot
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamScreenshotsNative
 * Method:    addScreenshotToLibrary
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamScreenshotsNative_addScreenshotToLibrary
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamScreenshotsNative
 * Method:    triggerScreenshot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamScreenshotsNative_triggerScreenshot
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamScreenshotsNative
 * Method:    hookScreenshots
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamScreenshotsNative_hookScreenshots
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamScreenshotsNative
 * Method:    setLocation
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamScreenshotsNative_setLocation
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamScreenshotsNative
 * Method:    tagUser
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamScreenshotsNative_tagUser
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamScreenshotsNative
 * Method:    tagPublishedFile
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamScreenshotsNative_tagPublishedFile
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamScreenshotsNative
 * Method:    isScreenshotsHooked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamScreenshotsNative_isScreenshotsHooked
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
