/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamHTTPNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamHTTPNative
#define _Included_org_twopology_steamnetworks4j_SteamHTTPNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    createCallback
 * Signature: (Lorg/twopology/steamnetworks4j/SteamHTTPCallbackAdapter;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    createHTTPRequest
 * Signature: (ZILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_createHTTPRequest
  (JNIEnv *, jclass, jboolean, jint, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    setHTTPRequestContextValue
 * Signature: (ZJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_setHTTPRequestContextValue
  (JNIEnv *, jclass, jboolean, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    setHTTPRequestNetworkActivityTimeout
 * Signature: (ZJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_setHTTPRequestNetworkActivityTimeout
  (JNIEnv *, jclass, jboolean, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    setHTTPRequestHeaderValue
 * Signature: (ZJLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_setHTTPRequestHeaderValue
  (JNIEnv *, jclass, jboolean, jlong, jstring, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    setHTTPRequestGetOrPostParameter
 * Signature: (ZJLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_setHTTPRequestGetOrPostParameter
  (JNIEnv *, jclass, jboolean, jlong, jstring, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    sendHTTPRequest
 * Signature: (ZJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_sendHTTPRequest
  (JNIEnv *, jclass, jboolean, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    sendHTTPRequestAndStreamResponse
 * Signature: (ZJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_sendHTTPRequestAndStreamResponse
  (JNIEnv *, jclass, jboolean, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    getHTTPResponseHeaderSize
 * Signature: (ZJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_getHTTPResponseHeaderSize
  (JNIEnv *, jclass, jboolean, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    getHTTPResponseHeaderValue
 * Signature: (ZJLjava/lang/String;Ljava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_getHTTPResponseHeaderValue
  (JNIEnv *, jclass, jboolean, jlong, jstring, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    getHTTPResponseBodySize
 * Signature: (ZJ)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_getHTTPResponseBodySize
  (JNIEnv *, jclass, jboolean, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    getHTTPResponseBodyData
 * Signature: (ZJLjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_getHTTPResponseBodyData
  (JNIEnv *, jclass, jboolean, jlong, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    getHTTPStreamingResponseBodyData
 * Signature: (ZJILjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_getHTTPStreamingResponseBodyData
  (JNIEnv *, jclass, jboolean, jlong, jint, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamHTTPNative
 * Method:    releaseHTTPRequest
 * Signature: (ZJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamHTTPNative_releaseHTTPRequest
  (JNIEnv *, jclass, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
