/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamControllerNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamControllerNative
#define _Included_org_twopology_steamnetworks4j_SteamControllerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_init
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    shutdown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    runFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_runFrame
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getConnectedControllers
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getConnectedControllers
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    showBindingPanel
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_showBindingPanel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getActionSetHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getActionSetHandle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    activateActionSet
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_activateActionSet
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getCurrentActionSet
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getCurrentActionSet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getDigitalActionHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getDigitalActionHandle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getDigitalActionData
 * Signature: (JJLorg/twopology/steamnetworks4j/SteamControllerDigitalActionData;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getDigitalActionData
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getDigitalActionOrigins
 * Signature: (JJJ[I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getDigitalActionOrigins
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getAnalogActionHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getAnalogActionHandle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getAnalogActionData
 * Signature: (JJLorg/twopology/steamnetworks4j/SteamControllerAnalogActionData;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getAnalogActionData
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getAnalogActionOrigins
 * Signature: (JJJ[I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getAnalogActionOrigins
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    stopAnalogActionMomentum
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_stopAnalogActionMomentum
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    triggerHapticPulse
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_triggerHapticPulse
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    triggerRepeatedHapticPulse
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_triggerRepeatedHapticPulse
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    triggerVibration
 * Signature: (JSS)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_triggerVibration
  (JNIEnv *, jclass, jlong, jshort, jshort);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    setLEDColor
 * Signature: (JBBBI)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_setLEDColor
  (JNIEnv *, jclass, jlong, jbyte, jbyte, jbyte, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getGamepadIndexForController
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getGamepadIndexForController
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getControllerForGamepadIndex
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getControllerForGamepadIndex
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getMotionData
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getMotionData
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getStringForActionOrigin
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getStringForActionOrigin
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getGlyphForActionOrigin
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getGlyphForActionOrigin
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamControllerNative
 * Method:    getInputTypeForHandle
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamControllerNative_getInputTypeForHandle
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
