/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamMatchmakingServersNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamMatchmakingServersNative
#define _Included_org_twopology_steamnetworks4j_SteamMatchmakingServersNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    requestInternetServerList
 * Signature: (I[Lorg/twopology/steamnetworks4j/SteamMatchmakingKeyValuePair;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_requestInternetServerList
  (JNIEnv *, jclass, jint, jobjectArray, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    requestLANServerList
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_requestLANServerList
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    requestFriendsServerList
 * Signature: (I[Lorg/twopology/steamnetworks4j/SteamMatchmakingKeyValuePair;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_requestFriendsServerList
  (JNIEnv *, jclass, jint, jobjectArray, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    requestFavoritesServerList
 * Signature: (I[Lorg/twopology/steamnetworks4j/SteamMatchmakingKeyValuePair;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_requestFavoritesServerList
  (JNIEnv *, jclass, jint, jobjectArray, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    requestHistoryServerList
 * Signature: (I[Lorg/twopology/steamnetworks4j/SteamMatchmakingKeyValuePair;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_requestHistoryServerList
  (JNIEnv *, jclass, jint, jobjectArray, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    requestSpectatorServerList
 * Signature: (I[Lorg/twopology/steamnetworks4j/SteamMatchmakingKeyValuePair;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_requestSpectatorServerList
  (JNIEnv *, jclass, jint, jobjectArray, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    releaseRequest
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_releaseRequest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    getServerDetails
 * Signature: (JILorg/twopology/steamnetworks4j/SteamMatchmakingGameServerItem;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_getServerDetails
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    cancelQuery
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_cancelQuery
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    refreshQuery
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_refreshQuery
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    isRefreshing
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_isRefreshing
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    getServerCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_getServerCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    refreshServer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_refreshServer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    pingServer
 * Signature: (ISJ)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_pingServer
  (JNIEnv *, jclass, jint, jshort, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    playerDetails
 * Signature: (ISJ)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_playerDetails
  (JNIEnv *, jclass, jint, jshort, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    serverRules
 * Signature: (ISJ)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_serverRules
  (JNIEnv *, jclass, jint, jshort, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingServersNative
 * Method:    cancelServerQuery
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingServersNative_cancelServerQuery
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
