/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamUserNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamUserNative
#define _Included_org_twopology_steamnetworks4j_SteamUserNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    createCallback
 * Signature: (Lorg/twopology/steamnetworks4j/SteamUserCallbackAdapter;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    getSteamID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_getSteamID
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    initiateGameConnection
 * Signature: (Ljava/nio/ByteBuffer;IIJISZ)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_initiateGameConnection
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jint, jshort, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    terminateGameConnection
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_terminateGameConnection
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    startVoiceRecording
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_startVoiceRecording
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    stopVoiceRecording
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_stopVoiceRecording
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    getAvailableVoice
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_getAvailableVoice
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    getVoice
 * Signature: (Ljava/nio/ByteBuffer;II[I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_getVoice
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    decompressVoice
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;II[II)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_decompressVoice
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jintArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    getVoiceOptimalSampleRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_getVoiceOptimalSampleRate
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    getAuthSessionTicket
 * Signature: (Ljava/nio/ByteBuffer;II[I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_getAuthSessionTicket
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    getAuthTicketForWebApi
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_getAuthTicketForWebApi
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    beginAuthSession
 * Signature: (Ljava/nio/ByteBuffer;IIJ)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_beginAuthSession
  (JNIEnv *, jclass, jobject, jint, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    endAuthSession
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_endAuthSession
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    cancelAuthTicket
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_cancelAuthTicket
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    userHasLicenseForApp
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_userHasLicenseForApp
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    requestEncryptedAppTicket
 * Signature: (JLjava/nio/ByteBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_requestEncryptedAppTicket
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    getEncryptedAppTicket
 * Signature: (Ljava/nio/ByteBuffer;II[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_getEncryptedAppTicket
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    isBehindNAT
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_isBehindNAT
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserNative
 * Method:    advertiseGame
 * Signature: (JIS)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamUserNative_advertiseGame
  (JNIEnv *, jclass, jlong, jint, jshort);

#ifdef __cplusplus
}
#endif
#endif
