/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamUGCNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamUGCNative
#define _Included_org_twopology_steamnetworks4j_SteamUGCNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    createCallback
 * Signature: (Lorg/twopology/steamnetworks4j/SteamUGCCallbackAdapter;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    createQueryUserUGCRequest
 * Signature: (IIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_createQueryUserUGCRequest
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    createQueryAllUGCRequest
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_createQueryAllUGCRequest
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    createQueryUGCDetailsRequest
 * Signature: ([JI)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_createQueryUGCDetailsRequest
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    sendQueryUGCRequest
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_sendQueryUGCRequest
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getQueryUGCResult
 * Signature: (JILorg/twopology/steamnetworks4j/SteamUGCDetails;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getQueryUGCResult
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getQueryUGCPreviewURL
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getQueryUGCPreviewURL
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getQueryUGCMetadata
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getQueryUGCMetadata
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getQueryUGCStatistic
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getQueryUGCStatistic
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getQueryUGCNumAdditionalPreviews
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getQueryUGCNumAdditionalPreviews
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getQueryUGCAdditionalPreview
 * Signature: (JIILorg/twopology/steamnetworks4j/SteamUGC/ItemAdditionalPreview;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getQueryUGCAdditionalPreview
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getQueryUGCNumKeyValueTags
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getQueryUGCNumKeyValueTags
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getQueryUGCKeyValueTag
 * Signature: (JII[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getQueryUGCKeyValueTag
  (JNIEnv *, jclass, jlong, jint, jint, jobjectArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    releaseQueryUserUGCRequest
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_releaseQueryUserUGCRequest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    addRequiredTag
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_addRequiredTag
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    addExcludedTag
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_addExcludedTag
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setReturnOnlyIDs
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setReturnOnlyIDs
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setReturnKeyValueTags
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setReturnKeyValueTags
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setReturnLongDescription
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setReturnLongDescription
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setReturnMetadata
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setReturnMetadata
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setReturnChildren
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setReturnChildren
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setReturnAdditionalPreviews
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setReturnAdditionalPreviews
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setReturnTotalOnly
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setReturnTotalOnly
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setReturnPlaytimeStats
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setReturnPlaytimeStats
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setLanguage
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setLanguage
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setAllowCachedResponse
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setAllowCachedResponse
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setCloudFileNameFilter
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setCloudFileNameFilter
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setMatchAnyTag
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setMatchAnyTag
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setSearchText
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setSearchText
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setRankedByTrendDays
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setRankedByTrendDays
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    addRequiredKeyValueTag
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_addRequiredKeyValueTag
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    requestUGCDetails
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_requestUGCDetails
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    createItem
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_createItem
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    startItemUpdate
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_startItemUpdate
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setItemTitle
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setItemTitle
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setItemDescription
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setItemDescription
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setItemUpdateLanguage
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setItemUpdateLanguage
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setItemMetadata
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setItemMetadata
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setItemVisibility
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setItemVisibility
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setItemTags
 * Signature: (J[Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setItemTags
  (JNIEnv *, jclass, jlong, jobjectArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setItemContent
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setItemContent
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setItemPreview
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setItemPreview
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    removeItemKeyValueTags
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_removeItemKeyValueTags
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    addItemKeyValueTag
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_addItemKeyValueTag
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    submitItemUpdate
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_submitItemUpdate
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getItemUpdateProgress
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getItemUpdateProgress
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    setUserItemVote
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_setUserItemVote
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getUserItemVote
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getUserItemVote
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    addItemToFavorites
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_addItemToFavorites
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    removeItemFromFavorites
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_removeItemFromFavorites
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    subscribeItem
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_subscribeItem
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    unsubscribeItem
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_unsubscribeItem
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getNumSubscribedItems
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getNumSubscribedItems
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getSubscribedItems
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getSubscribedItems
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getItemState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getItemState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getItemInstallInfo
 * Signature: (JLorg/twopology/steamnetworks4j/SteamUGC/ItemInstallInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getItemInstallInfo
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    getItemDownloadInfo
 * Signature: (J[J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_getItemDownloadInfo
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    deleteItem
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_deleteItem
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    downloadItem
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_downloadItem
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    initWorkshopForGameServer
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_initWorkshopForGameServer
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    suspendDownloads
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_suspendDownloads
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    startPlaytimeTracking
 * Signature: (J[JI)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_startPlaytimeTracking
  (JNIEnv *, jclass, jlong, jlongArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    stopPlaytimeTracking
 * Signature: (J[JI)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_stopPlaytimeTracking
  (JNIEnv *, jclass, jlong, jlongArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUGCNative
 * Method:    stopPlaytimeTrackingForAllItems
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUGCNative_stopPlaytimeTrackingForAllItems
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
