/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamNetworkingNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamNetworkingNative
#define _Included_org_twopology_steamnetworks4j_SteamNetworkingNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingNative
 * Method:    createCallback
 * Signature: (Lorg/twopology/steamnetworks4j/SteamNetworkingCallbackAdapter;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingNative
 * Method:    sendP2PPacket
 * Signature: (ZJLjava/nio/ByteBuffer;IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingNative_sendP2PPacket
  (JNIEnv *, jclass, jboolean, jlong, jobject, jint, jint, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingNative
 * Method:    isP2PPacketAvailable
 * Signature: (Z[II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingNative_isP2PPacketAvailable
  (JNIEnv *, jclass, jboolean, jintArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingNative
 * Method:    readP2PPacket
 * Signature: (ZLjava/nio/ByteBuffer;II[I[JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingNative_readP2PPacket
  (JNIEnv *, jclass, jboolean, jobject, jint, jint, jintArray, jlongArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingNative
 * Method:    acceptP2PSessionWithUser
 * Signature: (ZJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingNative_acceptP2PSessionWithUser
  (JNIEnv *, jclass, jboolean, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingNative
 * Method:    closeP2PSessionWithUser
 * Signature: (ZJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingNative_closeP2PSessionWithUser
  (JNIEnv *, jclass, jboolean, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingNative
 * Method:    closeP2PChannelWithUser
 * Signature: (ZJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingNative_closeP2PChannelWithUser
  (JNIEnv *, jclass, jboolean, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingNative
 * Method:    getP2PSessionState
 * Signature: (ZJLorg/twopology/steamnetworks4j/SteamNetworking/P2PSessionState;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingNative_getP2PSessionState
  (JNIEnv *, jclass, jboolean, jlong, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingNative
 * Method:    allowP2PPacketRelay
 * Signature: (ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingNative_allowP2PPacketRelay
  (JNIEnv *, jclass, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
