/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamUtilsNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamUtilsNative
#define _Included_org_twopology_steamnetworks4j_SteamUtilsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    createCallback
 * Signature: (Lorg/twopology/steamnetworks4j/SteamUtilsCallbackAdapter;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    getSecondsSinceAppActive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_getSecondsSinceAppActive
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    getSecondsSinceComputerActive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_getSecondsSinceComputerActive
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    getConnectedUniverse
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_getConnectedUniverse
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    getServerRealTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_getServerRealTime
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    getIPCountry
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_getIPCountry
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    getImageWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_getImageWidth
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    getImageHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_getImageHeight
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    getImageSize
 * Signature: (I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_getImageSize
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    getImageRGBA
 * Signature: (ILjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_getImageRGBA
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    getAppID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_getAppID
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    setOverlayNotificationPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_setOverlayNotificationPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    isAPICallCompleted
 * Signature: (J[Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_isAPICallCompleted
  (JNIEnv *, jclass, jlong, jbooleanArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    getAPICallFailureReason
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_getAPICallFailureReason
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    enableWarningMessageHook
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_enableWarningMessageHook
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    isOverlayEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_isOverlayEnabled
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    isSteamInBigPictureMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_isSteamInBigPictureMode
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    isSteamChinaLauncher
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_isSteamChinaLauncher
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    isSteamRunningOnSteamDeck
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_isSteamRunningOnSteamDeck
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    showFloatingGamepadTextInput
 * Signature: (IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_showFloatingGamepadTextInput
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    setGameLauncherMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_setGameLauncherMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    dismissFloatingGamepadTextInput
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_dismissFloatingGamepadTextInput
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUtilsNative
 * Method:    dismissGamepadTextInput
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUtilsNative_dismissGamepadTextInput
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
