/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamFriendsNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamFriendsNative
#define _Included_org_twopology_steamnetworks4j_SteamFriendsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    createCallback
 * Signature: (Lorg/twopology/steamnetworks4j/SteamFriendsCallbackAdapter;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getPersonaName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getPersonaName
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getPersonaState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getPersonaState
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getFriendCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getFriendCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getFriendByIndex
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getFriendByIndex
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getFriendRelationship
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getFriendRelationship
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getFriendPersonaState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getFriendPersonaState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getFriendPersonaName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getFriendPersonaName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getFriendGamePlayed
 * Signature: (JLorg/twopology/steamnetworks4j/SteamFriends/FriendGameInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getFriendGamePlayed
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    setInGameVoiceSpeaking
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_setInGameVoiceSpeaking
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getSmallFriendAvatar
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getSmallFriendAvatar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getMediumFriendAvatar
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getMediumFriendAvatar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getLargeFriendAvatar
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getLargeFriendAvatar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    requestUserInformation
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_requestUserInformation
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    activateGameOverlay
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_activateGameOverlay
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    activateGameOverlayToUser
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_activateGameOverlayToUser
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    activateGameOverlayToWebPage
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_activateGameOverlayToWebPage
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    activateGameOverlayToStore
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_activateGameOverlayToStore
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    setPlayedWith
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_setPlayedWith
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    activateGameOverlayInviteDialog
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_activateGameOverlayInviteDialog
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    setRichPresence
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_setRichPresence
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    clearRichPresence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_clearRichPresence
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getFriendRichPresence
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getFriendRichPresence
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getFriendRichPresenceKeyCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getFriendRichPresenceKeyCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getFriendRichPresenceKeyByIndex
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getFriendRichPresenceKeyByIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    requestFriendRichPresence
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_requestFriendRichPresence
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    inviteUserToGame
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_inviteUserToGame
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getCoplayFriendCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getCoplayFriendCount
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getCoplayFriend
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getCoplayFriend
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getFriendCoplayTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getFriendCoplayTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamFriendsNative
 * Method:    getFriendCoplayGame
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamFriendsNative_getFriendCoplayGame
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
