/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamRemoteStorageNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamRemoteStorageNative
#define _Included_org_twopology_steamnetworks4j_SteamRemoteStorageNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    createCallback
 * Signature: (Lorg/twopology/steamnetworks4j/SteamRemoteStorageCallbackAdapter;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileWrite
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileWrite
  (JNIEnv *, jclass, jstring, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileRead
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileRead
  (JNIEnv *, jclass, jstring, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileWriteAsync
 * Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileWriteAsync
  (JNIEnv *, jclass, jlong, jstring, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileReadAsync
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileReadAsync
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileReadAsyncComplete
 * Signature: (JLjava/nio/ByteBuffer;JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileReadAsyncComplete
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileForget
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileForget
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileDelete
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileDelete
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileShare
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileShare
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    setSyncPlatforms
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_setSyncPlatforms
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileWriteStreamOpen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileWriteStreamOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileWriteStreamWriteChunk
 * Signature: (JLjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileWriteStreamWriteChunk
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileWriteStreamClose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileWriteStreamClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileWriteStreamCancel
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileWriteStreamCancel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    fileExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_fileExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    filePersisted
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_filePersisted
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    getFileSize
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_getFileSize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    getFileTimestamp
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_getFileTimestamp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    getSyncPlatforms
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_getSyncPlatforms
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    getFileCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_getFileCount
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    getFileNameAndSize
 * Signature: (I[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_getFileNameAndSize
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    getQuota
 * Signature: ([J[J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_getQuota
  (JNIEnv *, jclass, jlongArray, jlongArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    isCloudEnabledForAccount
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_isCloudEnabledForAccount
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    isCloudEnabledForApp
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_isCloudEnabledForApp
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    setCloudEnabledForApp
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_setCloudEnabledForApp
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    ugcDownload
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_ugcDownload
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    getUGCDownloadProgress
 * Signature: (J[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_getUGCDownloadProgress
  (JNIEnv *, jclass, jlong, jintArray, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    ugcRead
 * Signature: (JLjava/nio/ByteBuffer;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_ugcRead
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    getCachedUGCCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_getCachedUGCCount
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    getCachedUGCHandle
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_getCachedUGCHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    publishWorkshopFile
 * Signature: (JLjava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I[Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_publishWorkshopFile
  (JNIEnv *, jclass, jlong, jstring, jstring, jint, jstring, jstring, jint, jobjectArray, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    createPublishedFileUpdateRequest
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_createPublishedFileUpdateRequest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    updatePublishedFileFile
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_updatePublishedFileFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    updatePublishedFilePreviewFile
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_updatePublishedFilePreviewFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    updatePublishedFileTitle
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_updatePublishedFileTitle
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    updatePublishedFileDescription
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_updatePublishedFileDescription
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    updatePublishedFileVisibility
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_updatePublishedFileVisibility
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    updatePublishedFileTags
 * Signature: (J[Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_updatePublishedFileTags
  (JNIEnv *, jclass, jlong, jobjectArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamRemoteStorageNative
 * Method:    commitPublishedFileUpdate
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamRemoteStorageNative_commitPublishedFileUpdate
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
