/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamID */

#ifndef _Included_org_twopology_steamnetworks4j_SteamID
#define _Included_org_twopology_steamnetworks4j_SteamID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamID
 * Method:    isValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamID_isValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamID
 * Method:    getInvalidSteamID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamID_getInvalidSteamID
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
