/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamNetworkingSocketsNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
#define _Included_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    initRelayNetworkAccess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_initRelayNetworkAccess
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    getRelayNetworkStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_getRelayNetworkStatus
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    createCallback
 * Signature: (Lorg/twopology/steamnetworks4j/SteamNetworkingSocketsCallback;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    connectP2P
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_connectP2P
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    createListenSocketP2P
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_createListenSocketP2P
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    acceptConnection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_acceptConnection
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    closeConnection
 * Signature: (IIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_closeConnection
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    closeListenSocket
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_closeListenSocket
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    sendMessageToConnection
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_sendMessageToConnection
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    receiveMessagesOnConnection
 * Signature: (I[Lorg/twopology/steamnetworks4j/SteamNetworkingMessage;I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_receiveMessagesOnConnection
  (JNIEnv *, jclass, jint, jobjectArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    flushMessages
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_flushMessages
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    createPollGroup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_createPollGroup
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    destroyPollGroup
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_destroyPollGroup
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    setConnectionPollGroup
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_setConnectionPollGroup
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    receiveMessagesOnPollGroup
 * Signature: (I[Lorg/twopology/steamnetworks4j/SteamNetworkingMessage;I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_receiveMessagesOnPollGroup
  (JNIEnv *, jclass, jint, jobjectArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    initAuthentication
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_initAuthentication
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamNetworkingSocketsNative
 * Method:    getAuthenticationStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamNetworkingSocketsNative_getAuthenticationStatus
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
