/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamMatchmakingRulesResponse */

#ifndef _Included_org_twopology_steamnetworks4j_SteamMatchmakingRulesResponse
#define _Included_org_twopology_steamnetworks4j_SteamMatchmakingRulesResponse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingRulesResponse
 * Method:    createProxy
 * Signature: (Lorg/twopology/steamnetworks4j/SteamMatchmakingRulesResponse;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingRulesResponse_createProxy
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
