/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamUserStatsNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamUserStatsNative
#define _Included_org_twopology_steamnetworks4j_SteamUserStatsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    createCallback
 * Signature: (Lorg/twopology/steamnetworks4j/SteamUserStatsCallbackAdapter;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getStat
 * Signature: (Ljava/lang/String;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getStat__Ljava_lang_String_2_3I
  (JNIEnv *, jclass, jstring, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    setStat
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_setStat__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getStat
 * Signature: (Ljava/lang/String;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getStat__Ljava_lang_String_2_3F
  (JNIEnv *, jclass, jstring, jfloatArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    setStat
 * Signature: (Ljava/lang/String;F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_setStat__Ljava_lang_String_2F
  (JNIEnv *, jclass, jstring, jfloat);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getAchievement
 * Signature: (Ljava/lang/String;[Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getAchievement
  (JNIEnv *, jclass, jstring, jbooleanArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    setAchievement
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_setAchievement
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    clearAchievement
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_clearAchievement
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    storeStats
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_storeStats
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    indicateAchievementProgress
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_indicateAchievementProgress
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getNumAchievements
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getNumAchievements
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getAchievementName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getAchievementName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    resetAllStats
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_resetAllStats
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    findOrCreateLeaderboard
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_findOrCreateLeaderboard
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    findLeaderboard
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_findLeaderboard
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getLeaderboardName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getLeaderboardName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getLeaderboardEntryCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getLeaderboardEntryCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getLeaderboardSortMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getLeaderboardSortMethod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getLeaderboardDisplayType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getLeaderboardDisplayType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    downloadLeaderboardEntries
 * Signature: (JJIII)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_downloadLeaderboardEntries
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    downloadLeaderboardEntriesForUsers
 * Signature: (JJ[JI)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_downloadLeaderboardEntriesForUsers
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getDownloadedLeaderboardEntry
 * Signature: (JILorg/twopology/steamnetworks4j/SteamLeaderboardEntry;[II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getDownloadedLeaderboardEntry__JILorg_twopology_steamnetworks4j_SteamLeaderboardEntry_2_3II
  (JNIEnv *, jclass, jlong, jint, jobject, jintArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getDownloadedLeaderboardEntry
 * Signature: (JILorg/twopology/steamnetworks4j/SteamLeaderboardEntry;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getDownloadedLeaderboardEntry__JILorg_twopology_steamnetworks4j_SteamLeaderboardEntry_2
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    uploadLeaderboardScore
 * Signature: (JJII[II)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_uploadLeaderboardScore__JJII_3II
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jintArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    uploadLeaderboardScore
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_uploadLeaderboardScore__JJII
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getNumberOfCurrentPlayers
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getNumberOfCurrentPlayers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    requestGlobalStats
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_requestGlobalStats
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getGlobalStat
 * Signature: (Ljava/lang/String;[J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getGlobalStat__Ljava_lang_String_2_3J
  (JNIEnv *, jclass, jstring, jlongArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getGlobalStat
 * Signature: (Ljava/lang/String;[D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getGlobalStat__Ljava_lang_String_2_3D
  (JNIEnv *, jclass, jstring, jdoubleArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getGlobalStatHistory
 * Signature: (Ljava/lang/String;[JI)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getGlobalStatHistory__Ljava_lang_String_2_3JI
  (JNIEnv *, jclass, jstring, jlongArray, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamUserStatsNative
 * Method:    getGlobalStatHistory
 * Signature: (Ljava/lang/String;[DI)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamUserStatsNative_getGlobalStatHistory__Ljava_lang_String_2_3DI
  (JNIEnv *, jclass, jstring, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
