/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamMatchmakingNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamMatchmakingNative
#define _Included_org_twopology_steamnetworks4j_SteamMatchmakingNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    createCallback
 * Signature: (Lorg/twopology/steamnetworks4j/SteamMatchmakingCallbackAdapter;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getFavoriteGameCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getFavoriteGameCount
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getFavoriteGame
 * Signature: (I[I[I[S[S[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getFavoriteGame
  (JNIEnv *, jclass, jint, jintArray, jintArray, jshortArray, jshortArray, jintArray, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    addFavoriteGame
 * Signature: (IISSII)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_addFavoriteGame
  (JNIEnv *, jclass, jint, jint, jshort, jshort, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    removeFavoriteGame
 * Signature: (IISSI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_removeFavoriteGame
  (JNIEnv *, jclass, jint, jint, jshort, jshort, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    requestLobbyList
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_requestLobbyList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    addRequestLobbyListStringFilter
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_addRequestLobbyListStringFilter
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    addRequestLobbyListNumericalFilter
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_addRequestLobbyListNumericalFilter
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    addRequestLobbyListNearValueFilter
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_addRequestLobbyListNearValueFilter
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    addRequestLobbyListFilterSlotsAvailable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_addRequestLobbyListFilterSlotsAvailable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    addRequestLobbyListDistanceFilter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_addRequestLobbyListDistanceFilter
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    addRequestLobbyListResultCountFilter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_addRequestLobbyListResultCountFilter
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    addRequestLobbyListCompatibleMembersFilter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_addRequestLobbyListCompatibleMembersFilter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getLobbyByIndex
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getLobbyByIndex
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    createLobby
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_createLobby
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    joinLobby
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_joinLobby
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    leaveLobby
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_leaveLobby
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    inviteUserToLobby
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_inviteUserToLobby
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getNumLobbyMembers
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getNumLobbyMembers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getLobbyMemberByIndex
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getLobbyMemberByIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getLobbyData
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getLobbyData
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    setLobbyData
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_setLobbyData
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getLobbyMemberData
 * Signature: (JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getLobbyMemberData
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    setLobbyMemberData
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_setLobbyMemberData
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getLobbyDataCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getLobbyDataCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getLobbyDataByIndex
 * Signature: (JILorg/twopology/steamnetworks4j/SteamMatchmakingKeyValuePair;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getLobbyDataByIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    deleteLobbyData
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_deleteLobbyData
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    sendLobbyChatMsg
 * Signature: (JLjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_sendLobbyChatMsg__JLjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    sendLobbyChatMsg
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_sendLobbyChatMsg__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getLobbyChatEntry
 * Signature: (JILorg/twopology/steamnetworks4j/SteamMatchmaking/ChatEntry;Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getLobbyChatEntry
  (JNIEnv *, jclass, jlong, jint, jobject, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    requestLobbyData
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_requestLobbyData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    setLobbyGameServer
 * Signature: (JISJ)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_setLobbyGameServer
  (JNIEnv *, jclass, jlong, jint, jshort, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getLobbyGameServer
 * Signature: (J[I[S[J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getLobbyGameServer
  (JNIEnv *, jclass, jlong, jintArray, jshortArray, jlongArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    setLobbyMemberLimit
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_setLobbyMemberLimit
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getLobbyMemberLimit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getLobbyMemberLimit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    setLobbyType
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_setLobbyType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    setLobbyJoinable
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_setLobbyJoinable
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    getLobbyOwner
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_getLobbyOwner
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    setLobbyOwner
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_setLobbyOwner
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamMatchmakingNative
 * Method:    setLinkedLobby
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamMatchmakingNative_setLinkedLobby
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
