/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamInterface */

#ifndef _Included_org_twopology_steamnetworks4j_SteamInterface
#define _Included_org_twopology_steamnetworks4j_SteamInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamInterface
 * Method:    deleteCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamInterface_deleteCallback
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
