/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamGameServerStatsNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamGameServerStatsNative
#define _Included_org_twopology_steamnetworks4j_SteamGameServerStatsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerStatsNative
 * Method:    createCallback
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerStatsNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerStatsNative
 * Method:    requestUserStats
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerStatsNative_requestUserStats
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerStatsNative
 * Method:    getUserStat
 * Signature: (JLjava/lang/String;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerStatsNative_getUserStat__JLjava_lang_String_2_3I
  (JNIEnv *, jclass, jlong, jstring, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerStatsNative
 * Method:    getUserStat
 * Signature: (JLjava/lang/String;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerStatsNative_getUserStat__JLjava_lang_String_2_3F
  (JNIEnv *, jclass, jlong, jstring, jfloatArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerStatsNative
 * Method:    getUserAchievement
 * Signature: (JLjava/lang/String;[Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerStatsNative_getUserAchievement
  (JNIEnv *, jclass, jlong, jstring, jbooleanArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerStatsNative
 * Method:    setUserStat
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerStatsNative_setUserStat__JLjava_lang_String_2I
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerStatsNative
 * Method:    setUserStat
 * Signature: (JLjava/lang/String;F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerStatsNative_setUserStat__JLjava_lang_String_2F
  (JNIEnv *, jclass, jlong, jstring, jfloat);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerStatsNative
 * Method:    updateUserAvgRateStat
 * Signature: (JLjava/lang/String;FD)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerStatsNative_updateUserAvgRateStat
  (JNIEnv *, jclass, jlong, jstring, jfloat, jdouble);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerStatsNative
 * Method:    setUserAchievement
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerStatsNative_setUserAchievement
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerStatsNative
 * Method:    clearUserAchievement
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerStatsNative_clearUserAchievement
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerStatsNative
 * Method:    storeUserStats
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerStatsNative_storeUserStats
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
