/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamGameServerNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamGameServerNative
#define _Included_org_twopology_steamnetworks4j_SteamGameServerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    createCallback
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_createCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setProduct
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setProduct
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setGameDescription
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setGameDescription
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setModDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setModDir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setDedicatedServer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setDedicatedServer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    logOn
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_logOn
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    logOnAnonymous
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_logOnAnonymous
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    logOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_logOff
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    isLoggedOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_isLoggedOn
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    isSecure
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_isSecure
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    getSteamID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_getSteamID
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    wasRestartRequested
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_wasRestartRequested
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setMaxPlayerCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setMaxPlayerCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setBotPlayerCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setBotPlayerCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setServerName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setServerName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setMapName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setMapName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setPasswordProtected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setPasswordProtected
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setSpectatorPort
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setSpectatorPort
  (JNIEnv *, jclass, jshort);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setSpectatorServerName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setSpectatorServerName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    clearAllKeyValues
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_clearAllKeyValues
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setKeyValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setKeyValue
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setGameTags
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setGameTags
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setGameData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setGameData
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    setRegion
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_setRegion
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    sendUserConnectAndAuthenticate
 * Signature: (ILjava/nio/ByteBuffer;II[J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_sendUserConnectAndAuthenticate
  (JNIEnv *, jclass, jint, jobject, jint, jint, jlongArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    createUnauthenticatedUserConnection
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_createUnauthenticatedUserConnection
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    sendUserDisconnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_sendUserDisconnect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    updateUserData
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_updateUserData
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    getAuthSessionTicket
 * Signature: (Ljava/nio/ByteBuffer;II[I)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_getAuthSessionTicket
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    beginAuthSession
 * Signature: (Ljava/nio/ByteBuffer;IIJ)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_beginAuthSession
  (JNIEnv *, jclass, jobject, jint, jint, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    endAuthSession
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_endAuthSession
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    cancelAuthTicket
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_cancelAuthTicket
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    userHasLicenseForApp
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_userHasLicenseForApp
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    requestUserGroupStatus
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_requestUserGroupStatus
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    getPublicIP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_getPublicIP
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    handleIncomingPacket
 * Signature: (Ljava/nio/ByteBuffer;IIIS)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_handleIncomingPacket
  (JNIEnv *, jclass, jobject, jint, jint, jint, jshort);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    getNextOutgoingPacket
 * Signature: (Ljava/nio/ByteBuffer;II[I[S)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_getNextOutgoingPacket
  (JNIEnv *, jclass, jobject, jint, jint, jintArray, jshortArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    associateWithClan
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_associateWithClan
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNative
 * Method:    computeNewPlayerCompatibility
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNative_computeNewPlayerCompatibility
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
