/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamGameServerNetworkingNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamGameServerNetworkingNative
#define _Included_org_twopology_steamnetworks4j_SteamGameServerNetworkingNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerNetworkingNative
 * Method:    createCallback
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerNetworkingNative_createCallback
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
