/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative
#define _Included_org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative
 * Method:    decryptTicket
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;II[BI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative_decryptTicket
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jbyteArray, jint, jintArray);

/*
 * Class:     org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative
 * Method:    isTicketForApp
 * Signature: (Ljava/nio/ByteBuffer;III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative_isTicketForApp
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative
 * Method:    getTicketIssueTime
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative_getTicketIssueTime
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative
 * Method:    getTicketSteamID
 * Signature: (Ljava/nio/ByteBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative_getTicketSteamID
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative
 * Method:    getTicketAppID
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative_getTicketAppID
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative
 * Method:    userOwnsAppInTicket
 * Signature: (Ljava/nio/ByteBuffer;III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative_userOwnsAppInTicket
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative
 * Method:    userIsVacBanned
 * Signature: (Ljava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative_userIsVacBanned
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative
 * Method:    getUserVariableData
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_twopology_steamnetworks4j_SteamEncryptedAppTicketNative_getUserVariableData
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
