/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamGameServerAPINative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamGameServerAPINative
#define _Included_org_twopology_steamnetworks4j_SteamGameServerAPINative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerAPINative
 * Method:    nativeInit
 * Signature: (ISSILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerAPINative_nativeInit
  (JNIEnv *, jclass, jint, jshort, jshort, jint, jstring);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerAPINative
 * Method:    nativeShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerAPINative_nativeShutdown
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerAPINative
 * Method:    runCallbacks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerAPINative_runCallbacks
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerAPINative
 * Method:    isSecure
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerAPINative_isSecure
  (JNIEnv *, jclass);

/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerAPINative
 * Method:    nativeGetSteamID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerAPINative_nativeGetSteamID
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
