/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twopology_steamnetworks4j_SteamGameServerHTTPNative */

#ifndef _Included_org_twopology_steamnetworks4j_SteamGameServerHTTPNative
#define _Included_org_twopology_steamnetworks4j_SteamGameServerHTTPNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twopology_steamnetworks4j_SteamGameServerHTTPNative
 * Method:    createCallback
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_twopology_steamnetworks4j_SteamGameServerHTTPNative_createCallback
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
